
spring:
  datasource:
    url: jdbc:postgresql://172.30.1.54:5432/mydb
    username: jaehyun
    password: 111111!!
  data:
    redis:
      host: 172.30.1.54
      port: 6379
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  secret: jjjhhhyyyuunnn1241241241k2j4b12jk4b1j4k
  access-token-validity: 1800000     # 30분
  refresh-token-validity: 604800000  # 7일
